name: sleec-runtime-enforcer

services:

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - enforcer-network

  asmeta-server:
    build:
        context: ./asmeta_server
    ports:
      - "8080:8080"
    networks:
      - enforcer-network

  enforcer:
    build:
      context: ./enforcer
    environment:
      SERVER_IP: asmeta-server
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
      MODEL: ${MODEL}
      MODEL_HEADER: ${MODEL_HEADER}
    depends_on:
      - asmeta-server
    networks:
      - enforcer-network

  firefighter-sim-comm-layer:
    profiles: ["firefighter-sim"]
    build:
      context: ./ros2_ws
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
    entrypoint: "/bin/bash -c 'source /opt/ros/humble/setup.bash && source /ros2_ws/install/setup.bash && ros2 launch firefighter_comm_layer firefighter_comm_layer_launch.py rabbitmq_user:=${RABBITMQ_DEFAULT_USER:-guest} rabbitmq_pass:=${RABBITMQ_DEFAULT_USER:-guest}'"
    networks:
      - enforcer-network

  firefighter-sim:
    profiles: ["firefighter-sim"]
    build:
      context: ./ros2_ws    
    entrypoint: "/bin/bash -c 'source /opt/ros/humble/setup.bash && source /ros2_ws/install/setup.bash && ros2 launch firefighter_sim firefighter_sim_launch.py'"
    networks:
      - enforcer-network

networks:
  enforcer-network:
    # driver: bridge